name: Secret Scanning Workflow

on:
  workflow_call: # Define this workflow as reusable
    secrets: # Allows the calling workflow to pass secrets
      GITHUB_TOKEN: {}
      GITLEAKS_LICENSE: {}

jobs:
  scan:
    name: Gitleaks Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Using secrets directly
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
