name: Secret Scanning Workflow

on:
  workflow_call:
    inputs:
      branches:
        description: 'Branches to trigger secret scanning'
        required: true
        default: ['main', 'master']
      github_token:
       description: 'GitHub Token for authentication'
       required: true
      gitleaks_license:
       description: 'Gitleaks license token'
       required: false

jobs:
  scan:
    name: Gitleaks Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
          GITLEAKS_LICENSE: ${{ inputs.gitleaks_license }}
