name: Secret Scanning Workflow

on:
  workflow_call:

jobs:
  scan:
    name: Gitleaks Secret Scanning
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # GITHUB_TOKEN is provided automatically by GitHub
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # GITHUB_TOKEN is provided automatically by GitHub
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
