name: Quarterly Repo Audit

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'  # Run quarterly on the 1st of Jan, Apr, Jul, Oct at midnight
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure write permissions are granted

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install required dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run your Python script to generate a new CSV in the audit folder
    - name: Run repository audit script
      env:
        GITHUB_PAT: ${{ secrets.PAT_TOKEN }}  # Use the PAT_TOKEN instead of GITHUB_TOKEN
      run: |
        mkdir -p audit  # Create the audit folder if it doesn't exist
        TIMESTAMP=$(date +'%Y%m%d-%H%M%S')  # Create a timestamp
        python audit/getAllOrgSecretScanAudit.py -pat ${{ secrets.PAT_TOKEN }} -org DevSecOps-AppSec -output audit/repos_data_$TIMESTAMP.csv  # Output new file to audit folder
        ls -la audit  # List the files in the audit folder for debugging

    # Step 5: Configure git
    - name: Configure git
      run: |
        git config --global user.name 'souro1212'
        git config --global user.email 'souradip1212@gmail.com'

    # Step 6: Pull latest changes
    - name: Pull latest changes
      run: git pull origin main

    # Step 7: Add and commit the new files
    - name: Add and commit changes
      run: |
        git add audit/*.csv  # Add all CSV files in the audit folder
        git commit -m 'Add new repository audit CSV file'

    # Step 8: Force push changes to the repository
    - name: Force push changes
      env:
        GH_PAT: ${{ secrets.PAT_TOKEN }}  # Use Personal Access Token from secrets
      run: |
        git push --force https://$GH_PAT@github.com/${{ github.repository }}.git HEAD:main
        
