name: Quarterly Repo Audit
permissions:
  contents: write  # Grant write permissions to the GITHUB_TOKEN
  
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'  # Run quarterly on the 1st of Jan, Apr, Jul, Oct at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install required dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the repository audit script
    - name: Run repository audit script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        python audit/getAllOrgSecretScanAudit.py -pat ${{ secrets.PAT_TOKEN }} -org DevSecOps-AppSec

    # Step 5: Create a new branch for the changes
    - name: Create new branch
      run: |
        BRANCH_NAME="update-repo-audit-$(date +'%Y%m%d-%H%M%S')"
        git checkout -b $BRANCH_NAME
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add repos_data.csv
        git commit -m "Update repo audit CSV file (Quarterly)"
        git push https://<YOUR_USERNAME>:${{ secrets.PAT_TOKEN }}@github.com/DevSecOps-AppSec/reusable-workflows.git $BRANCH_NAME

    # Step 6: Create a pull request
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_TOKEN }}
        branch: ${{ steps.create_branch.outputs.BRANCH_NAME }}
        title: "Update repo audit CSV file (Quarterly)"
        body: "This pull request contains the updated repo audit CSV file."
        base: main  # Target the main branch for the PR

    # Step 7: Send CSV file to Slack channel
    - name: Send file to Slack
      run: |
        curl -F file=@repos_data.csv \
             -F "initial_comment=Here is the updated repo audit CSV file for this quarter." \
             -F channels=<YOUR_SLACK_CHANNEL_ID> \
             -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
             https://slack.com/api/files.upload
             
