name: Quarterly Repo Audit

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'  # Run quarterly on the 1st of Jan, Apr, Jul, Oct at midnight
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure write permissions are granted

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install required dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run your Python script to generate a new CSV in the audit folder
    - name: Run repository audit script
      env:
        GITHUB_PAT: ${{ secrets.PAT_TOKEN }}  # Use the PAT_TOKEN instead of GITHUB_TOKEN
      run: |
        mkdir -p audit  # Create the audit folder if it doesn't exist
        TIMESTAMP=$(date +'%Y%m%d-%H%M%S')  # Create a timestamp
        python audit/getAllOrgSecretScanAudit.py -pat ${{ secrets.PAT_TOKEN }} -org DevSecOps-AppSec -output audit/repos_data_$TIMESTAMP.csv  # Output new file to audit folder

    # Step 5: Configure git with the PAT user's credentials
    - name: Configure git with PAT user
      run: |
        git config --global user.name 'souro1212'  # Use the PAT user's name
        git config --global user.email 'souradip1212@gmail.com'  # Use the PAT user's email

    # Step 6: Create new branch
    - name: Create new branch
      run: |
        BRANCH_NAME="update-repo-audit-$(date +'%Y%m%d-%H%M%S')"
        git checkout -b $BRANCH_NAME
        git add audit/*.csv
        git commit -m 'Add new repository audit CSV file'
        git push https://$GH_PAT@github.com/${{ github.repository }}.git $BRANCH_NAME

    # Step 7: Create a pull request
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT_TOKEN }}
        branch: $BRANCH_NAME
        title: "Update repo audit CSV file"
        body: "This pull request contains the updated repo audit CSV file."
        base: main
