name: Quarterly Repo Audit
permissions:
  contents: write  # Grant write permissions to the GITHUB_TOKEN
  
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'  # Run quarterly on the 1st of Jan, Apr, Jul, Oct at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install required dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the repository audit script
    - name: Run repository audit script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python audit/getAllOrgSecretScanAudit.py -pat ${{ secrets.GITHUB_TOKEN }} -org DevSecOps-AppSec

    # Step 5: Commit CSV file
    - name: Commit CSV File
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add repos_data.csv
        git commit -m "Update repo audit CSV file (Quarterly)"
        git push

    # Step 6: Send CSV file to Slack channel
    - name: Send file to Slack
      run: |
        curl -F file=@repos_data.csv \
             -F "initial_comment=Here is the updated repo audit CSV file for this quarter." \
             -F channels=<YOUR_SLACK_CHANNEL_ID> \
             -H "Authorization: Bearer ${{ secrets.SLACK_WEBHOOK_URL }}" \
             https://slack.com/api/files.upload
